create table public.trail_condition_snapshots (
  id bigint generated by default as identity primary key,
  snapshot_date date not null default ((now() at time zone 'America/Los_Angeles')::date),
  fetched_at timestamptz not null default now(),
  payload jsonb not null,
  source_status jsonb not null default '{}'::jsonb,
  constraint trail_condition_snapshots_snapshot_date_key unique (snapshot_date),
  constraint trail_condition_snapshots_payload_object
    check (jsonb_typeof(payload) = 'object'),
  constraint trail_condition_snapshots_source_status_object
    check (jsonb_typeof(source_status) = 'object')
);

comment on table public.trail_condition_snapshots is
  'Daily server-side snapshot of route water, smoke, fire, closure, bridge, and agency-alert sources.';

create index trail_condition_snapshots_fetched_at_idx
  on public.trail_condition_snapshots (fetched_at desc);

alter table public.trail_condition_snapshots enable row level security;

create policy "team can view trail condition snapshots"
on public.trail_condition_snapshots
for select
to authenticated
using ((select private.is_ddg_team_member()));

revoke all on table public.trail_condition_snapshots from anon;
grant select on table public.trail_condition_snapshots to authenticated;
grant all on table public.trail_condition_snapshots to service_role;
grant usage, select on sequence public.trail_condition_snapshots_id_seq to service_role;
