-- Combined schema + optional RLS policies for DDG Mission Control

-- ═══════════════════════════════════════════════════════════════════════════════
-- CORE TABLES
-- ═══════════════════════════════════════════════════════════════════════════════

create table if not exists ops_logs (
  id bigint generated by default as identity primary key,
  created_at timestamptz default timezone('utc'::text, now()) not null,
  context_id text not null,
  user_name text not null,
  content text not null,
  type text default 'NOTE' not null check (type in ('NOTE','TASK','ALERT')),
  status text check (status is null or status in ('OPEN','IN_PROGRESS','DONE'))
);

alter table if exists ops_logs
  add column if not exists status text check (status is null or status in ('OPEN','IN_PROGRESS','DONE'));

create table if not exists gear_loadouts (
  hiker_id text primary key,
  updated_at timestamptz default timezone('utc'::text, now()) not null,
  item_ids jsonb default '[]'::jsonb
);

create table if not exists custom_items (
  id bigint generated by default as identity primary key,
  created_at timestamptz default timezone('utc'::text, now()) not null,
  name text not null,
  detail text,
  weight_val numeric,
  weight_label text,
  category text default 'Custom',
  module_id text default 'custom',
  source_ids jsonb default '[]'::jsonb,
  created_by text
);

-- ═══════════════════════════════════════════════════════════════════════════════
-- AUTH TABLES (for DDG team access control)
-- ═══════════════════════════════════════════════════════════════════════════════

create table if not exists allowed_emails (
  id bigint generated by default as identity primary key,
  email text not null unique,
  hiker_id text,
  name text,
  added_at timestamptz default now()
);

create table if not exists access_requests (
  id bigint generated by default as identity primary key,
  email text not null unique,
  requested_at timestamptz default now(),
  status text default 'pending' check (status in ('pending', 'approved', 'denied')),
  reviewed_by text,
  reviewed_at timestamptz,
  notes text
);

create table if not exists ddg_team_profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text not null unique,
  hiker_id text not null,
  name text not null,
  role text default 'member',
  created_at timestamptz default now(),
  last_seen timestamptz
);

-- ═══════════════════════════════════════════════════════════════════════════════
-- REALTIME PUBLICATION
-- ═══════════════════════════════════════════════════════════════════════════════
do $$
begin
  if not exists (select 1 from pg_publication_tables where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'ops_logs') then
    alter publication supabase_realtime add table ops_logs;
  end if;
end $$;

do $$
begin
  if not exists (select 1 from pg_publication_tables where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'gear_loadouts') then
    alter publication supabase_realtime add table gear_loadouts;
  end if;
end $$;

do $$
begin
  if not exists (select 1 from pg_publication_tables where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'custom_items') then
    alter publication supabase_realtime add table custom_items;
  end if;
end $$;

-- Seed baseline loadouts
insert into gear_loadouts (hiker_id, item_ids)
values ('dan','[]'),('drew','[]'),('gunnar','[]')
on conflict (hiker_id) do nothing;

-- Seed allowed emails for DDG team
insert into allowed_emails (email, hiker_id, name)
values
  ('smileyguy@aol.com', 'dan', 'Dan'),
  ('andrew.d.hostetler@gmail.com', 'drew', 'Drew'),
  ('gunnarguy@me.com', 'gunnar', 'Gunnar'),
  ('gunnarguy@aol.com', 'gunnar', 'Gunnar')
on conflict (email) do nothing;

-- Enable RLS (required for PostgREST + realtime). Policies below are permissive for anon key
-- so the current open-access behavior is preserved while silencing Supabase warnings.
alter table ops_logs enable row level security;
alter table gear_loadouts enable row level security;
alter table custom_items enable row level security;
alter table ddg_team_profiles enable row level security;
alter table access_requests enable row level security;
alter table allowed_emails enable row level security;

-- Reset policies so re-running this script is idempotent
drop policy if exists "ops_logs_select_all" on ops_logs;
drop policy if exists "ops_logs_insert_all" on ops_logs;
drop policy if exists "ops_logs_update_status" on ops_logs;

drop policy if exists "gear_loadouts_select_all" on gear_loadouts;
drop policy if exists "gear_loadouts_upsert_all" on gear_loadouts;
drop policy if exists "gear_loadouts_update_all" on gear_loadouts;

drop policy if exists "custom_items_select_all" on custom_items;
drop policy if exists "custom_items_insert_all" on custom_items;
drop policy if exists "custom_items_update_all" on custom_items;

drop policy if exists "ddg_team_profiles_select_own" on ddg_team_profiles;
drop policy if exists "ddg_team_profiles_select_all" on ddg_team_profiles;

drop policy if exists "access_requests_insert" on access_requests;
drop policy if exists "access_requests_select_admin" on access_requests;

drop policy if exists "allowed_emails_select_all" on allowed_emails;

-- Permissive policies (anonymous read/write). Tighten as needed when auth is added.
create policy "ops_logs_select_all" on ops_logs for select using (true);
create policy "ops_logs_insert_all" on ops_logs for insert with check (true);
create policy "ops_logs_update_status" on ops_logs for update using (true) with check (true);

create policy "gear_loadouts_select_all" on gear_loadouts for select using (true);
create policy "gear_loadouts_upsert_all" on gear_loadouts for insert with check (true);
create policy "gear_loadouts_update_all" on gear_loadouts for update using (true) with check (true);

create policy "custom_items_select_all" on custom_items for select using (true);
create policy "custom_items_insert_all" on custom_items for insert with check (true);
create policy "custom_items_update_all" on custom_items for update using (true) with check (true);

-- Auth table policies (team members can view profiles, anyone can request access)
create policy "ddg_team_profiles_select_own" on ddg_team_profiles for select using (auth.uid() = id);
create policy "ddg_team_profiles_select_all" on ddg_team_profiles for select using (true);

create policy "access_requests_insert" on access_requests for insert with check (true);
create policy "access_requests_select_admin" on access_requests for select using (true);

create policy "allowed_emails_select_all" on allowed_emails for select using (true);
