-- Supabase schema for DDG Mission Control
-- Run in SQL editor or via supabase CLI

-- Ops log table
create table if not exists ops_logs (
  id bigint generated by default as identity primary key,
  created_at timestamptz default timezone('utc'::text, now()) not null,
  context_id text not null,
  user_name text not null,
  content text not null,
  type text default 'NOTE' not null check (type in ('NOTE','TASK','ALERT')),
  status text check (status is null or status in ('OPEN','IN_PROGRESS','DONE'))
);

-- Backfill status column if migrating an existing table
alter table if exists ops_logs
  add column if not exists status text check (status is null or status in ('OPEN','IN_PROGRESS','DONE'));

-- Gear loadouts per hiker
create table if not exists gear_loadouts (
  hiker_id text primary key,
  updated_at timestamptz default timezone('utc'::text, now()) not null,
  item_ids jsonb default '[]'::jsonb
);

-- Custom gear items (shared inventory)
create table if not exists custom_items (
  id bigint generated by default as identity primary key,
  created_at timestamptz default timezone('utc'::text, now()) not null,
  name text not null,
  detail text,
  weight_val numeric,
  weight_label text,
  category text default 'Custom',
  module_id text default 'custom',
  source_ids jsonb default '[]'::jsonb,
  created_by text
);

-- Realtime publication
alter publication supabase_realtime add table ops_logs;
alter publication supabase_realtime add table gear_loadouts;
alter publication supabase_realtime add table custom_items;

-- Seed baseline loadouts
insert into gear_loadouts (hiker_id, item_ids)
values ('dan','[]'),('drew','[]'),('gunnar','[]')
on conflict (hiker_id) do nothing;
